# Generated by Django 3.1.4 on 2021-04-15 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contact', phone_field.models.PhoneField(max_length=31)),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('image', models.ImageField(upload_to='images/')),
                ('hunger', models.BooleanField()),
                ('homeless', models.BooleanField()),
                ('women', models.BooleanField()),
                ('children', models.BooleanField()),
                ('elderly', models.BooleanField()),
                ('cancer', models.BooleanField()),
                ('differently_abled', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
